secureConnect:
  oauth2:
    endpoint: https://<baseurl>/oauth/token
    clientid: <client-id>
    clientsecret: <client-secret>
  connect:
    urls:
      url-name: https://<host>/some/url
      another-url: https://<host>/another/{}/url